# This workflow will build a docker container, publish it to IBM Container Registry, and deploy it to an existing IKS cluster

name: Build and Deploy to IKS

# Execute on every push to the default branch. Merging a pull request counts as a push.
on:
  push:
    branches:
      - master
  release:
    types: # This configuration does not affect the page_build event above
      - created
      
jobs:
  build-push-deploy-job:
    runs-on: ubuntu-latest
    name: A job to download and log into ibmcloud cli
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variables
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
        env:
          VCAP_LOCAL: ${{ secrets.VCAP_LOCAL }}
          REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.REACT_APP_MAPBOX_ACCESS_TOKEN }}
        run: |
          echo "$VCAP_LOCAL" >> ./web/api/vcap-local.json
          echo REACT_APP_MAPBOX_ACCESS_TOKEN=$REACT_APP_MAPBOX_ACCESS_TOKEN >> ./web/client/.env.local

